### ISSUE TITLE
Thanks for this project

### ISSUE THREAD

**Issue by ghost** [svenevs/nanogui-customization-demo#1]
Any idea why Python does not recognize the lib?
![image](https://user-images.githubusercontent.com/18743986/93518844-1428f480-f936-11ea-8b98-895ed5ee54e0.png)

![image](https://user-images.githubusercontent.com/18743986/93518937-33c01d00-f936-11ea-9184-3f0bdb87aab7.png)

Thanks,

**Comment by svenevs** [comment]
You'll need to configure your editor to see the CMake build tree, or install the python library manually.  See also https://github.com/mitsuba-renderer/nanogui/issues/57#issuecomment-698176568 this is a failed prototype

**Comment by svenevs** [comment]
Sorry again, I completely forgot about this repo. Added deprecation notice https://github.com/svenevs/nanogui-customization-demo/commit/78863bbdbe19544438f6e8b66faa8a69b1a58a33
